import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, FileText, Lock, MessageSquare, Users } from "lucide-react";
import { audit, auditEvents, evidence } from "@/lib/demo-data";
import { CardHeader, ConfidencePill, PageHeader, ProvenanceLine, Signal, StatusPill } from "@/components/ui";

const stages = ["Draft", "Data Validation", "Technical Review", "Client Review", "Approved", "Superseded"];
export default async function AuditPage({ params }: { params: Promise<{ id: string }> }) {
  await params;
  return <div className="content"><PageHeader eyebrow="Audit workspace / AUD-2026-014" title="Detailed audit workspace" description="A reviewable evidence boundary for the Pune Plant. Technical outputs are versioned, traceable, and require human approval." actions={<><Link className="btn" href="/overview"><ArrowLeft className="svg-icon" /> Overview</Link><Link className="btn primary" href="/reports"><FileText className="svg-icon" /> Report preview</Link></>} />
    <div className="card"><div style={{display:"flex",justifyContent:"space-between",gap:20,flexWrap:"wrap"}}><div><StatusPill tone="iris">{audit.state}</StatusPill><h2 style={{fontSize:24,marginTop:15}}>{audit.name}</h2><p className="card-subtitle" style={{maxWidth:650}}>{audit.purpose}</p></div><div style={{textAlign:"right"}}><div className="kicker">Readiness</div><div className="big-number">{audit.completeness}%</div><div className="card-subtitle">Grade B · reviewer-led</div></div></div><div className="stage">{stages.map((stage, index) => <div key={stage} className={`stage-step ${index < 2 ? "done" : index === 2 ? "current" : ""}`}><div><div className="stage-dot">{index < 2 ? "✓" : index + 1}</div><div className="stage-name">{stage}</div></div></div>)}</div><ProvenanceLine source={{sourceId:"AUDIT-SNAPSHOT-014-v3",unit:"snapshot",status:"calculated",confidence:"B",assumptions:["Approved outputs remain immutable"],formulaVersion:"workflow-2026.01"}} /></div>
    <div className="grid two section"><div className="card"><CardHeader title="Audit definition" subtitle="Scope and methodology metadata" /><div className="detail-grid"><div className="detail"><span>Audit level</span><strong>{audit.level}</strong></div><div className="detail"><span>Reporting period</span><strong>{audit.period}</strong></div><div className="detail"><span>Boundary</span><strong>{audit.boundary}</strong></div><div className="detail"><span>Owner</span><strong>{audit.owner}</strong></div><div className="detail"><span>Reviewer</span><strong>{audit.reviewer}</strong></div><div className="detail"><span>Methodology</span><strong>IPMVP-informed screening</strong></div><div className="detail"><span>Operating schedule</span><strong>2 shifts · 6 days/week</strong></div><div className="detail"><span>Inclusions</span><strong>Utilities + production</strong></div></div><Signal type="info">This is decision-support software. It does not provide statutory BEE certification, PAT filing, legal compliance approval, or professional auditor certification.</Signal></div><div className="card"><CardHeader title="Review controls" subtitle="Role-aware workflow actions" /><div className="alert"><Users className="svg-icon" style={{color:"var(--pale)"}} /><div><strong>Technical reviewer assigned</strong><span>{audit.reviewer} · 3 open comments</span></div></div><div className="alert"><Lock className="svg-icon" style={{color:"var(--cyan)"}} /><div><strong>Approval creates an immutable snapshot</strong><span>Later edits create a new audit version.</span></div></div><button className="btn primary" style={{marginTop:16,width:"100%"}}><CheckCircle2 className="svg-icon" /> Request technical approval</button><p className="footer-note">Available to Energy Auditor and Reviewer roles only. Demo access is shown as the auditor role.</p></div></div>
    <div className="grid two section"><div className="card"><CardHeader title="Evidence register" subtitle="Approved sources referenced by this audit" /><table className="mini-table"><thead><tr><th>ID</th><th>Evidence</th><th>Status</th><th className="right">Grade</th></tr></thead><tbody>{evidence.map((item) => <tr key={item.id}><td className="mono-value">{item.id}</td><td><div>{item.title}</div><div className="card-subtitle">{item.type} · {item.date}</div></td><td><StatusPill tone={item.status === "measured" ? "good" : "warn"}>{item.status}</StatusPill></td><td className="right"><ConfidencePill grade={item.confidence} /></td></tr>)}</tbody></table></div><div className="card"><CardHeader title="Recent actions" subtitle="Append-only audit history" /><div className="alert-list">{auditEvents.map((event) => <div className="alert" key={event.date}><MessageSquare className="svg-icon" style={{color:event.tone === "iris" ? "var(--iris)" : "var(--cyan)"}} /><div><strong>{event.text}</strong><span>{event.actor} · {event.date}</span></div></div>)}</div><div style={{marginTop:16}}><Link className="btn small" href="/settings">View audit log <ArrowRight className="svg-icon" /></Link></div></div></div>
  </div>;
}
