import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api-helpers";
import { canWrite, requireWorkspaceContext } from "@/lib/auth";
import { getSupabaseServerClient } from "@/lib/supabase/server";

const schema = z.object({ siteId: z.string().uuid(), code: z.string().trim().min(2).max(80), name: z.string().trim().min(2).max(200), level: z.string().trim().min(2).max(80), periodStart: z.string().date(), periodEnd: z.string().date(), boundary: z.string().trim().max(500).optional(), purpose: z.string().trim().max(1000).optional() });
export async function GET() { try { const context = await requireWorkspaceContext(); const supabase = await getSupabaseServerClient(); const { data, error } = await supabase.from("audits").select("id,site_id,code,name,level,period_start,period_end,state,completeness,boundary,purpose,created_at").eq("organization_id", context.organizationId).order("created_at", { ascending: false }); if (error) throw error; return NextResponse.json({ data }); } catch (error) { return apiError(error, "Unable to load audits."); } }
export async function POST(request: Request) { try { const context = await requireWorkspaceContext(); if (!canWrite(context.membership.role)) throw new Error("FORBIDDEN"); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Provide a valid site, code, name, level, and audit period." }, { status: 400 }); const supabase = await getSupabaseServerClient(); const { data: site } = await supabase.from("sites").select("id").eq("id", parsed.data.siteId).eq("organization_id", context.organizationId).maybeSingle(); if (!site) return NextResponse.json({ error: "Site is not in your organization." }, { status: 403 }); const { data, error } = await supabase.from("audits").insert({ organization_id: context.organizationId, site_id: parsed.data.siteId, code: parsed.data.code, name: parsed.data.name, level: parsed.data.level, period_start: parsed.data.periodStart, period_end: parsed.data.periodEnd, state: "Draft", completeness: 0, owner_name: context.user.user_metadata?.full_name || context.user.email || "Workspace user", boundary: parsed.data.boundary ?? "", purpose: parsed.data.purpose ?? "" }).select("id,code,name,state").single(); if (error) throw error; await supabase.from("audit_events").insert({ organization_id: context.organizationId, audit_id: data.id, event_type: "audit_created", actor_name: context.user.email ?? context.user.id, details: { code: data.code } }); return NextResponse.json({ data }, { status: 201 }); } catch (error) { return apiError(error, "Unable to create audit."); } }
