import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api-helpers";
import { canManageMembers, requireWorkspaceContext, roles } from "@/lib/auth";
import { getSupabaseServerClient } from "@/lib/supabase/server";

const schema = z.object({ id: z.string().uuid(), role: z.enum(roles), status: z.enum(["active", "invited", "suspended"]).optional() });
export async function GET() { try { const context = await requireWorkspaceContext(); if (!canManageMembers(context.membership.role)) throw new Error("FORBIDDEN"); const supabase = await getSupabaseServerClient(); const { data, error } = await supabase.from("organization_memberships").select("id,user_id,role,status,created_at").eq("organization_id", context.organizationId).order("created_at"); if (error) throw error; return NextResponse.json({ data }); } catch (error) { return apiError(error, "Unable to load organization members."); } }
export async function PATCH(request: Request) { try { const context = await requireWorkspaceContext(); if (!canManageMembers(context.membership.role)) throw new Error("FORBIDDEN"); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Membership update is invalid." }, { status: 400 }); if (parsed.data.id === context.membership.id && parsed.data.role !== "Admin") return NextResponse.json({ error: "Keep at least one administrator in the organization." }, { status: 400 }); const supabase = await getSupabaseServerClient(); const { data, error } = await supabase.from("organization_memberships").update({ role: parsed.data.role, ...(parsed.data.status ? { status: parsed.data.status } : {}) }).eq("id", parsed.data.id).eq("organization_id", context.organizationId).select("id,user_id,role,status").maybeSingle(); if (error) throw error; if (!data) return NextResponse.json({ error: "Membership not found." }, { status: 404 }); await supabase.from("audit_events").insert({ organization_id: context.organizationId, event_type: "membership_updated", actor_name: context.user.email ?? context.user.id, details: { membership_id: data.id, role: data.role, status: data.status } }); return NextResponse.json({ data }); } catch (error) { return apiError(error, "Unable to update membership."); } }
export async function DELETE(request: Request) { try { const context = await requireWorkspaceContext(); if (!canManageMembers(context.membership.role)) throw new Error("FORBIDDEN"); const id = new URL(request.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "Membership ID is required." }, { status: 400 }); if (id === context.membership.id) return NextResponse.json({ error: "You cannot remove your own active membership." }, { status: 400 }); const supabase = await getSupabaseServerClient(); const { error } = await supabase.from("organization_memberships").delete().eq("id", id).eq("organization_id", context.organizationId); if (error) throw error; await supabase.from("audit_events").insert({ organization_id: context.organizationId, event_type: "membership_removed", actor_name: context.user.email ?? context.user.id, details: { membership_id: id } }); return NextResponse.json({ ok: true }); } catch (error) { return apiError(error, "Unable to remove membership."); } }
