import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleAlert, ClipboardCheck, Plus } from "lucide-react";
import { completenessAlerts, endUses } from "@/lib/demo-data";
import { getWorkspaceSnapshot } from "@/lib/data-access";
import { specificEnergyConsumption } from "@/lib/calculations";
import { CardHeader, ConfidencePill, MetricCard, PageHeader, StatusPill } from "@/components/ui";
import { EnergyTrendChart } from "@/components/energy-chart";
import { RankingChart } from "@/components/ranking-chart";
import { Donut } from "@/components/donut";

export default async function OverviewPage() {
  const snapshot = await getWorkspaceSnapshot();
  const { audit, ecms, monthly, overviewMetrics } = snapshot;
  const annualElectricity = monthly.reduce((sum, item) => sum + item.electricity, 0);
  const totalProduction = monthly.reduce((sum, item) => sum + item.production, 0);
  const annualSec = specificEnergyConsumption(annualElectricity, totalProduction);
  const totalEcmSavings = ecms.reduce((sum, item) => sum + item.costSavings, 0);
  const maxEndUse = Math.max(...endUses.map((item) => item.value));
  return <div className="content"><PageHeader eyebrow="Portfolio / Pune Plant" title="Good morning, Ananya." description="A grounded view of where energy is moving, what is ready for review, and which decisions have the strongest evidence." actions={<><Link className="btn" href="/data"><Plus className="svg-icon" /> Add evidence</Link><Link className="btn primary" href="/reports"><ClipboardCheck className="svg-icon" /> Review report</Link></>} />
    <div className="grid metrics"><MetricCard label="Annual energy" value={overviewMetrics.annualEnergy.display} detail={`${(annualElectricity/1000).toFixed(0)} MWh electricity`} provenance={overviewMetrics.annualEnergy.provenance} /><MetricCard label="Annual energy cost" value={overviewMetrics.annualCost.display} detail="₹8.35 / kWh effective tariff" tone="inverted" provenance={overviewMetrics.annualCost.provenance} /><MetricCard label="Scope 1 + 2 emissions" value={overviewMetrics.emissions.display} detail="0.708 tCO₂e / MWh grid factor" provenance={overviewMetrics.emissions.provenance} /><MetricCard label="Renewable share" value={overviewMetrics.renewable.display} detail="On-site PV · measured output" provenance={overviewMetrics.renewable.provenance} /></div>
    <div className="grid three section"><div className="card"><div className="kicker">Significant energy uses</div><div className="big-number" style={{margin:"8px 0 3px"}}>5</div><div className="card-subtitle">Ranked by annual electricity allocation</div></div><div className="card"><div className="kicker">Maximum demand</div><div className="big-number" style={{margin:"8px 0 3px"}}>842 <small style={{fontSize:13,color:"var(--ash)"}}>kVA</small></div><div className="card-subtitle">91% of 925 kVA contract demand</div></div><div className="card"><div className="kicker">Specific energy</div><div className="big-number" style={{margin:"8px 0 3px"}}>{annualSec.toFixed(1)} <small style={{fontSize:13,color:"var(--ash)"}}>kWh/unit</small></div><div className="card-subtitle"><span className="trend-up">↓ 4.6%</span> vs FY24–25 baseline</div></div></div>
    <div className="grid two section"><div className="card"><EnergyTrendChart data={monthly} /></div><div className="card"><CardHeader title="Energy by end use" subtitle="Bottom-up allocation · calculated" action={<StatusPill tone="cyan">2.51 GWh</StatusPill>} />{endUses.map((item) => <div className="bar-row" key={item.name}><div className="bar-label">{item.name}</div><div className="bar-track"><div className="bar-fill" style={{width:`${item.value/maxEndUse*100}%`,background:item.color}} /></div><div className="bar-value">{(item.value/1000).toFixed(0)} MWh</div></div>)}<div className="source-line"><span>CALC-BAL-014</span> allocation · Grade B · 5% tolerance</div></div></div>
    <div className="grid two section"><div className="card"><CardHeader title="ECM impact · annual savings" subtitle="Screened opportunities · no double counting within interaction groups" action={<Link href="/ecms" className="btn small">Open register <ArrowRight className="svg-icon" /></Link>} /><RankingChart items={ecms} /><div className="source-line"><span>7 opportunities</span> · ₹{(totalEcmSavings/100000).toFixed(1)}L gross screened savings · 0.77 ktCO₂e</div></div><div className="card"><CardHeader title="Review health" subtitle="Evidence and workflow readiness" /><Donut value={audit.completeness} label="Data completeness" /><div style={{marginTop:22}}>{completenessAlerts.map((item) => <div className="alert" key={item.label}><div className={`alert-mark ${item.tone}`} /><div><strong>{item.label}</strong><span>{item.detail}</span></div></div>)}</div></div></div>
    <div className="grid two section"><div className="card"><CardHeader title="Audit workflow" subtitle={audit.name} action={<Link href={`/audits/${audit.id}`} className="btn small">Open audit <ArrowRight className="svg-icon" /></Link>} /><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><StatusPill tone="iris">{audit.state}</StatusPill><span className="card-subtitle">Last review · 18 Jun 2026</span></div><div className="progress"><span style={{width:`${audit.completeness}%`}} /></div><div className="source-line">{audit.completeness}% complete · owner {audit.owner}</div></div><div className="card"><CardHeader title="Approval queue" subtitle="Items needing a human decision" /><div className="alert"><CircleAlert className="svg-icon" style={{color:"#f4ad56"}} /><div><strong>3 technical observations</strong><span>Need reviewer comment before client review</span></div></div><div className="alert"><CheckCircle2 className="svg-icon" style={{color:"var(--cyan)"}} /><div><strong>ECM-05 demand management</strong><span>Approved · M&V method assigned</span></div></div></div></div>
  </div>;
}
