import Link from "next/link";
import { ArrowRight, ClipboardCheck, Plus } from "lucide-react";
import { getWorkspaceSnapshot } from "@/lib/data-access";
import { specificEnergyConsumption } from "@/lib/calculations";
import { CardHeader, MetricCard, PageHeader, StatusPill } from "@/components/ui";
import { EnergyTrendChart } from "@/components/energy-chart";
import { RankingChart } from "@/components/ranking-chart";
import { Donut } from "@/components/donut";
import { WorkspaceEmptyState } from "@/components/workspace-empty-state";

export default async function OverviewPage() {
  const snapshot = await getWorkspaceSnapshot();
  const { audit, ecms, monthly, overviewMetrics } = snapshot;
  if (snapshot.source === "supabase" && (!snapshot.company || !audit || !overviewMetrics)) return <div className="content"><PageHeader eyebrow="Workspace / setup" title="Build your first evidence-led workspace." description="This organization has no audit records yet. Start with a site and audit, then add bills, assets, and evidence as they become available." actions={<Link className="btn primary" href="/onboarding"><Plus className="svg-icon" /> Add site</Link>} /><WorkspaceEmptyState title="No audit data yet" description="Create the first site during onboarding, then create an audit and import its source records. Trancense will show real totals only after validated records exist." href="/onboarding" action="Open onboarding" /></div>;
  if (!audit || !overviewMetrics) return null;
  const annualElectricity = monthly.reduce((sum, item) => sum + item.electricity, 0);
  const totalProduction = monthly.reduce((sum, item) => sum + item.production, 0);
  const annualSec = specificEnergyConsumption(annualElectricity, totalProduction);
  const totalEcmSavings = ecms.reduce((sum, item) => sum + item.costSavings, 0);
  const endUses = snapshot.endUses;
  const maxEndUse = Math.max(...endUses.map((item) => item.value), 1);
  return <div className="content"><PageHeader eyebrow={`Portfolio / ${snapshot.company?.site ?? "Workspace"}`} title={snapshot.source === "demo" ? "Good morning, Ananya." : "Workspace overview"} description="A grounded view of where energy is moving, what is ready for review, and which decisions have the strongest evidence." actions={<><Link className="btn" href="/data"><Plus className="svg-icon" /> Add evidence</Link><Link className="btn primary" href="/reports"><ClipboardCheck className="svg-icon" /> Review report</Link></>} />
    <div className="grid metrics"><MetricCard label="Annual energy" value={overviewMetrics.annualEnergy.display} detail={`${(annualElectricity / 1000).toFixed(0)} MWh electricity`} provenance={overviewMetrics.annualEnergy.provenance} /><MetricCard label="Annual energy cost" value={overviewMetrics.annualCost.display} detail="Persisted bill totals" tone="inverted" provenance={overviewMetrics.annualCost.provenance} /><MetricCard label="Scope 1 + 2 emissions" value={overviewMetrics.emissions.display} detail="Configured factor context" provenance={overviewMetrics.emissions.provenance} /><MetricCard label="Renewable share" value={overviewMetrics.renewable.display} detail="Persisted solar output" provenance={overviewMetrics.renewable.provenance} /></div>
    <div className="grid three section"><div className="card"><div className="kicker">Significant energy uses</div><div className="big-number" style={{ margin: "8px 0 3px" }}>{endUses.length || "—"}</div><div className="card-subtitle">{endUses.length ? "Ranked by persisted allocation" : "No allocation records yet"}</div></div><div className="card"><div className="kicker">Utility bill records</div><div className="big-number" style={{ margin: "8px 0 3px" }}>{monthly.length}</div><div className="card-subtitle">Persisted billing periods</div></div><div className="card"><div className="kicker">Specific energy</div><div className="big-number" style={{ margin: "8px 0 3px" }}>{totalProduction ? annualSec.toFixed(1) : "—"} <small style={{ fontSize: 13, color: "var(--ash)" }}>{totalProduction ? "kWh/unit" : "awaiting production"}</small></div><div className="card-subtitle">Calculated from persisted production records</div></div></div>
    <div className="grid two section"><div className="card"><EnergyTrendChart data={monthly} /></div><div className="card"><CardHeader title="Energy by end use" subtitle="Persisted allocation · calculated" action={endUses.length ? <StatusPill tone="cyan">{(endUses.reduce((sum, item) => sum + item.value, 0) / 1000).toFixed(0)} MWh</StatusPill> : undefined} />{endUses.length ? endUses.map((item) => <div className="bar-row" key={item.name}><div className="bar-label">{item.name}</div><div className="bar-track"><div className="bar-fill" style={{ width: `${item.value / maxEndUse * 100}%`, background: item.color }} /></div><div className="bar-value">{(item.value / 1000).toFixed(0)} MWh</div></div>) : <div className="empty-note">No bottom-up allocation is stored for this organization yet.</div>}</div></div>
    <div className="grid two section"><div className="card"><CardHeader title="ECM impact · annual savings" subtitle="Persisted opportunities · review before approval" action={<Link href="/ecms" className="btn small">Open register <ArrowRight className="svg-icon" /></Link>} />{ecms.length ? <><RankingChart items={ecms} /><div className="source-line"><span>{ecms.length} opportunities</span> · ₹{(totalEcmSavings / 100000).toFixed(1)}L gross screened savings</div></> : <div className="empty-note">Create the first ECM after an audit observation has been validated.</div>}</div><div className="card"><CardHeader title="Review health" subtitle="Evidence and workflow readiness" /><Donut value={audit.completeness} label="Data completeness" /><div className="empty-note" style={{ marginTop: 22 }}>Completeness is recorded on the audit and must be reviewed by an authorized auditor.</div></div></div>
    <div className="grid two section"><div className="card"><CardHeader title="Audit workflow" subtitle={audit.name} action={<Link href={`/audits/${audit.id}`} className="btn small">Open audit <ArrowRight className="svg-icon" /></Link>} /><div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 12 }}><StatusPill tone="iris">{audit.state}</StatusPill><span className="card-subtitle">Persisted audit record</span></div><div className="progress"><span style={{ width: `${audit.completeness}%` }} /></div><div className="source-line">{audit.completeness}% complete · owner {audit.owner}</div></div><div className="card"><CardHeader title="Approval queue" subtitle="Human decisions only" /><div className="empty-note">Approval items will appear here after a reviewer creates a workflow transition.</div></div></div>
  </div>;
}
