import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api-helpers";
import { requireWorkspaceContext } from "@/lib/auth";
import { getSupabaseServerClient } from "@/lib/supabase/server";

const schema = z.object({ auditId: z.string().uuid().optional(), code: z.string().trim().min(2).max(80), title: z.string().trim().min(2).max(200), observation: z.string().trim().min(2).max(2000), proposedAction: z.string().trim().min(2).max(2000), systemName: z.string().trim().max(120).optional() });
const patchSchema = z.object({ id: z.string().uuid(), status: z.enum(["Identified", "Screened", "Approved", "In progress"]) });
export async function GET() { try { const context = await requireWorkspaceContext(); const supabase = await getSupabaseServerClient(); const { data, error } = await supabase.from("ecms").select("*").eq("organization_id", context.organizationId).order("created_at"); if (error) throw error; return NextResponse.json({ data }); } catch (error) { return apiError(error, "Unable to load ECMs."); } }
export async function POST(request: Request) { try { const context = await requireWorkspaceContext(); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Provide an ECM code, title, observation, and action." }, { status: 400 }); const supabase = await getSupabaseServerClient(); if (parsed.data.auditId) { const { data: audit } = await supabase.from("audits").select("id").eq("id", parsed.data.auditId).eq("organization_id", context.organizationId).maybeSingle(); if (!audit) return NextResponse.json({ error: "Audit is not in your organization." }, { status: 403 }); } const { data, error } = await supabase.from("ecms").insert({ organization_id: context.organizationId, audit_id: parsed.data.auditId ?? null, code: parsed.data.code, title: parsed.data.title, system_name: parsed.data.systemName ?? null, observation: parsed.data.observation, proposed_action: parsed.data.proposedAction, status: "Identified", confidence: "C", provenance: { source: "user-entered observation", formulaVersion: "screening-pending" } }).select("id,code,title,status").single(); if (error) throw error; await supabase.from("audit_events").insert({ organization_id: context.organizationId, audit_id: parsed.data.auditId ?? null, event_type: "ecm_created", actor_name: context.user.email ?? context.user.id, details: { ecm_id: data.id } }); return NextResponse.json({ data }, { status: 201 }); } catch (error) { return apiError(error, "Unable to create ECM."); } }
export async function PATCH(request: Request) { try { const context = await requireWorkspaceContext(); const parsed = patchSchema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "ECM status is invalid." }, { status: 400 }); const supabase = await getSupabaseServerClient(); const { data, error } = await supabase.from("ecms").update({ status: parsed.data.status }).eq("id", parsed.data.id).eq("organization_id", context.organizationId).select("id,status").maybeSingle(); if (error) throw error; if (!data) return NextResponse.json({ error: "ECM not found in your organization." }, { status: 404 }); await supabase.from("audit_events").insert({ organization_id: context.organizationId, event_type: "ecm_status_changed", actor_name: context.user.email ?? context.user.id, details: { ecm_id: data.id, status: data.status } }); return NextResponse.json({ data }); } catch (error) { return apiError(error, "Unable to update ECM."); } }
