import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api-helpers";
import { canManageMembers, requireWorkspaceContext, roles } from "@/lib/auth";
import { getSupabaseAdmin } from "@/lib/supabase-admin";
import { getSupabaseServerClient } from "@/lib/supabase/server";

const schema = z.object({ email: z.string().email(), role: z.enum(roles).default("Executive/Viewer") });
export async function POST(request: Request) { try { const context = await requireWorkspaceContext(); if (!canManageMembers(context.membership.role)) throw new Error("FORBIDDEN"); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Provide a valid tester email and role." }, { status: 400 }); const admin = getSupabaseAdmin(); if (!admin) return NextResponse.json({ error: "Server setup is incomplete: SUPABASE_SERVICE_ROLE_KEY is missing." }, { status: 503 }); const origin = new URL(request.url).origin; const { data: invited, error: inviteError } = await admin.auth.admin.inviteUserByEmail(parsed.data.email, { redirectTo: `${origin}/auth/callback` }); if (inviteError || !invited.user) throw inviteError ?? new Error("Invitation failed"); const supabase = await getSupabaseServerClient(); const { data, error } = await supabase.from("organization_memberships").upsert({ organization_id: context.organizationId, user_id: invited.user.id, role: parsed.data.role, status: "invited", invited_by: context.user.id }, { onConflict: "organization_id,user_id" }).select("id,user_id,role,status").single(); if (error) throw error; await supabase.from("audit_events").insert({ organization_id: context.organizationId, event_type: "tester_invited", actor_name: context.user.email ?? context.user.id, details: { membership_id: data.id } }); return NextResponse.json({ data: { id: data.id, status: data.status } }, { status: 201 }); } catch (error) { return apiError(error, "Unable to invite tester."); } }
