"use client";

import { useState } from "react";
import { ArrowUp, Bot, FileSearch, ShieldAlert } from "lucide-react";
import { energyBalance, ecms, evidence } from "@/lib/demo-data";
import { ProvenanceLine, StatusPill } from "./ui";

const prompts = ["Explain why the energy-balance variance is high.", "Summarize the top three ECMs for management.", "What evidence is missing before the pump VFD ECM is investment-grade?", "Draft the executive summary from approved calculations."];
function answerFor(prompt: string) { if (prompt.includes("variance")) return <>The balance is high because utility input is <strong>{(energyBalance.utility/1000000).toFixed(2)} GWh</strong> while the current bottom-up allocation covers <strong>{(energyBalance.endUse/1000000).toFixed(2)} GWh</strong>. The remaining <strong>{(energyBalance.unallocated/1000).toFixed(0)} MWh</strong> is explicitly unallocated, not a measured loss. Validate submeter coverage and schedule factors before treating it as an engineering conclusion.</>; if (prompt.includes("top three")) return <>For management, the shortest screened paybacks are <strong>compressed-air leakage repair</strong>, <strong>demand management scheduling</strong>, and <strong>compressor pressure reset</strong>. Their current combined screen is about <strong>₹{((ecms[0].costSavings+ecms[4].costSavings+ecms[1].costSavings)/100000).toFixed(1)}L/year</strong>; ECM-01 and ECM-02 share interaction group CA-01, so do not add their savings without a combined model.</>; if (prompt.includes("pump")) return <>Before the pump VFD ECM is investment-grade, collect a longer flow/differential-pressure/kW baseline, confirm the critical index, validate operating hours, and document the control sequence. Current evidence is Grade C for the measure and covers 5 of 7 sampled days.</>; return <>The approved calculation snapshot describes a {"Detailed"} audit for Pune Plant covering FY25–26. It reports {(energyBalance.utility/1000000).toFixed(2)} GWh of electricity input and keeps the visible balance variance and assumptions attached to the executive narrative.</>; }
export function AssistantPanel() { const [prompt,setPrompt] = useState(""); const [answer,setAnswer] = useState<string | null>(null); function ask(value:string) { setPrompt(value); setAnswer(value); } return <><div className="card" style={{background:"linear-gradient(135deg,#262439,#2e2e2e 58%,#23333a)"}}><div className="kicker" style={{color:"var(--pale)"}}>Grounded demo response</div><h2 style={{fontSize:24,marginTop:10}}>Ask from the evidence, not around it.</h2><p className="card-subtitle" style={{maxWidth:620}}>The fallback assistant is deterministic. It can explain calculations and approved evidence; it will not invent readings, savings, compliance status, or confidence.</p><div className="prompt-chips">{prompts.map((item) => <button className="chip" key={item} onClick={() => ask(item)}>{item}</button>)}</div><div style={{display:"flex",gap:8}}><input className="input" style={{flex:1}} placeholder="Ask a grounded question…" value={prompt} onChange={(e)=>setPrompt(e.target.value)} onKeyDown={(e)=>{if(e.key === "Enter" && prompt) ask(prompt)}} /><button className="btn primary" aria-label="Ask assistant" onClick={()=>prompt && ask(prompt)}><ArrowUp className="svg-icon" /></button></div></div>{answer ? <div className="card section"><div className="card-header"><div><div className="kicker">Grounded Demo Response</div><h2 style={{marginTop:8}}>{answer}</h2></div><Bot className="svg-icon" style={{color:"var(--iris)"}} /></div><div className="answer">{answerFor(answer)}</div><div className="grid three" style={{marginTop:22}}><div><div className="kicker">Calculations</div><div className="source-line"><span>CALC-BAL-014</span><span>CALC-ECM-01</span></div></div><div><div className="kicker">Evidence</div><div className="source-line"><span>EV-0307</span><span>{evidence[2].id}</span></div></div><div><div className="kicker">Mode</div><StatusPill tone="cyan">No API key · deterministic</StatusPill></div></div><ProvenanceLine source={{sourceId:"ASSIST-DEMO-01",unit:"grounded response",status:"AI-described",confidence:"B",assumptions:["Only seeded calculations and approved evidence are used"],formulaVersion:"assistant-demo-2026.01"}} /></div> : <div className="card section"><div className="empty-note"><FileSearch className="svg-icon" style={{color:"var(--cyan)",verticalAlign:"middle",marginRight:8}} /> Choose a prompt to see citations, assumptions, calculation IDs, and guardrail language.</div></div>}<div className="card section"><div className="alert"><ShieldAlert className="svg-icon" style={{color:"#f4ad56"}} /><div><strong>Guardrail active</strong><span>Requests for statutory certification, legal compliance conclusions, automatic equipment control, or invented evidence are refused.</span></div></div></div></>; }
