import { NextResponse } from "next/server";
import { z } from "zod";
import { apiError } from "@/lib/api-helpers";
import { requireWorkspaceContext } from "@/lib/auth";
import { getSupabaseServerClient } from "@/lib/supabase/server";

const schema = z.object({ auditId: z.string().uuid().optional(), code: z.string().trim().min(2).max(80), name: z.string().trim().min(2).max(160), inputs: z.record(z.string(), z.number()), outputs: z.record(z.string(), z.number()), assumptions: z.array(z.string().max(500)).max(30) });
export async function GET() { try { const context = await requireWorkspaceContext(); const supabase = await getSupabaseServerClient(); const { data, error } = await supabase.from("solar_scenarios").select("*").eq("organization_id", context.organizationId).order("created_at", { ascending: false }); if (error) throw error; return NextResponse.json({ data }); } catch (error) { return apiError(error, "Unable to load solar scenarios."); } }
export async function POST(request: Request) { try { const context = await requireWorkspaceContext(); const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: "Solar scenario data is invalid." }, { status: 400 }); const supabase = await getSupabaseServerClient(); if (parsed.data.auditId) { const { data: audit } = await supabase.from("audits").select("id").eq("id", parsed.data.auditId).eq("organization_id", context.organizationId).maybeSingle(); if (!audit) return NextResponse.json({ error: "Audit is not in your organization." }, { status: 403 }); } const { data, error } = await supabase.from("solar_scenarios").insert({ organization_id: context.organizationId, audit_id: parsed.data.auditId ?? null, code: parsed.data.code, name: parsed.data.name, inputs: parsed.data.inputs, outputs: parsed.data.outputs, assumptions: parsed.data.assumptions }).select("id,code,name").single(); if (error) throw error; return NextResponse.json({ data }, { status: 201 }); } catch (error) { return apiError(error, "Unable to create solar scenario."); } }
