import Link from "next/link";
import { ArrowRight, Building2, CircleAlert, Gauge } from "lucide-react";
import { assets } from "@/lib/demo-data";
import { getWorkspaceSnapshot } from "@/lib/data-access";
import { CardHeader, ConfidencePill, PageHeader, StatusPill } from "@/components/ui";

export default async function AssetsPage() {
  const snapshot = await getWorkspaceSnapshot();
  const visibleAssets = snapshot.assets.length ? snapshot.assets : assets;
  return <div className="content">
    <PageHeader eyebrow="Operations / asset hierarchy" title="Know what is using the energy." description="A reviewable hierarchy from organization to sensor, with linked evidence, health context, and the measures that touch each system." actions={<Link className="btn primary" href="/data#upload"><Building2 className="svg-icon" /> Import asset CSV</Link>} />
    <div className="grid two"><div className="card"><CardHeader title="Asset hierarchy" subtitle="Organization → site → area → system → equipment" /><div className="tree"><div className="tree-node"><Building2 className="svg-icon" style={{verticalAlign:"middle",color:"var(--iris)"}} /> <strong>Shakti Precision Components Pvt. Ltd.</strong><span>ORG-001</span></div><div className="tree-node level-1"><strong>Pune Plant</strong><span>SITE-PN-01 · Maharashtra</span></div><div className="tree-node level-2"><strong>Building A / Production</strong><span>Machining · assembly · lighting</span></div><div className="tree-node level-3"><strong>Production motors</strong><span>12 equipment · 3 meters</span></div><div className="tree-node level-2"><strong>Utility block</strong><span>HVAC · compressed air · DG</span></div><div className="tree-node level-3"><strong>Compressed air</strong><span>2 compressors · 1 pressure sensor</span></div><div className="tree-node level-3"><strong>HVAC</strong><span>4 pumps/fans · 2 temperature sensors</span></div><div className="tree-node level-2"><strong>Roof</strong><span>Planning area · PV scenario</span></div></div><div className="source-line"><span>ASSET-SNAPSHOT-04</span> 9 assets · 14 linked readings</div></div><div className="card"><CardHeader title="Fleet health" subtitle="Evidence-backed signals, not predictive maintenance" /><div className="split-stat"><div><span>Healthy / operating</span><strong style={{display:"block"}}>6 / 9</strong></div><StatusPill tone="good">67%</StatusPill></div><div className="split-stat"><div><span>Needs review</span><strong style={{display:"block"}}>3</strong></div><StatusPill tone="warn">Attention</StatusPill></div><div className="split-stat"><div><span>Critical assets</span><strong style={{display:"block"}}>4</strong></div><StatusPill tone="iris">Protected</StatusPill></div><div className="alert" style={{marginTop:18}}><CircleAlert className="svg-icon" style={{color:"#f4ad56"}} /><div><strong>3 equipment records below Grade B</strong><span>Review evidence before using them in investment-grade calculations.</span></div></div></div></div>
    <div className="card table-card section"><CardHeader title="Equipment register" subtitle="Stable IDs make asset evidence traceable" action={<Link href="/ecms" className="btn small">View related ECMs <ArrowRight className="svg-icon" /></Link>} /><div className="table-scroll"><table className="data-table"><thead><tr><th>Equipment</th><th>System / location</th><th>Rating</th><th>Health</th><th>Criticality</th><th>Confidence</th><th>Status</th></tr></thead><tbody>{visibleAssets.map((asset) => <tr key={asset.id}><td><strong>{asset.name}</strong><div className="card-subtitle">{asset.id} · {asset.kind}</div></td><td>{asset.system}<div className="card-subtitle">{asset.location}</div></td><td className="mono-value">{asset.rating}</td><td><div style={{display:"flex",alignItems:"center",gap:8}}><Gauge className="svg-icon" style={{color:asset.health < 75 ? "#f4ad56" : "var(--cyan)"}} />{asset.health}%</div></td><td><StatusPill tone={asset.criticality === "High" ? "orchid" : "default"}>{asset.criticality}</StatusPill></td><td><ConfidencePill grade={asset.confidence} /></td><td><StatusPill tone={asset.status === "Operating" ? "good" : asset.status === "Needs review" ? "warn" : "default"}>{asset.status}</StatusPill></td></tr>)}</tbody></table></div></div>
  </div>;
}
