import Link from "next/link";
import { ArrowRight, Building2, CircleAlert, Gauge } from "lucide-react";
import { getWorkspaceSnapshot } from "@/lib/data-access";
import { CardHeader, ConfidencePill, PageHeader, StatusPill } from "@/components/ui";
import { WorkspaceEmptyState } from "@/components/workspace-empty-state";

export default async function AssetsPage() {
  const snapshot = await getWorkspaceSnapshot();
  const visibleAssets = snapshot.assets;
  if (snapshot.source === "supabase" && !visibleAssets.length) return <div className="content"><PageHeader eyebrow="Operations / asset hierarchy" title="Know what is using the energy." description="Add real equipment records to build the organization-to-meter hierarchy." actions={<Link className="btn primary" href="/data#upload"><Building2 className="svg-icon" /> Import asset CSV</Link>} /><WorkspaceEmptyState title="No assets yet" description="Import your first asset register or add equipment records from an authorized workspace role. No health or energy metrics are shown until records exist." href="/data#upload" action="Import asset CSV" /></div>;
  const healthy = visibleAssets.filter((asset) => asset.status === "Operating").length;
  const needsReview = visibleAssets.filter((asset) => asset.status === "Needs review").length;
  return <div className="content"><PageHeader eyebrow={`Operations / ${snapshot.company?.site ?? "asset hierarchy"}`} title="Know what is using the energy." description="A reviewable hierarchy from organization to equipment, with linked evidence and health context." actions={<Link className="btn primary" href="/data#upload"><Building2 className="svg-icon" /> Import asset CSV</Link>} />
    <div className="grid two"><div className="card"><CardHeader title="Asset hierarchy" subtitle="Organization → site → equipment" /><div className="tree"><div className="tree-node"><Building2 className="svg-icon" style={{ verticalAlign: "middle", color: "var(--iris)" }} /> <strong>{snapshot.company?.name ?? "Organization"}</strong><span>Tenant-scoped</span></div><div className="tree-node level-1"><strong>{snapshot.company?.site ?? "Site"}</strong><span>{snapshot.company?.region ?? "Region not recorded"}</span></div>{visibleAssets.slice(0, 7).map((asset) => <div className="tree-node level-2" key={asset.id}><strong>{asset.name}</strong><span>{asset.system} · {asset.location}</span></div>)}</div><div className="source-line"><span>Persisted asset register</span> · {visibleAssets.length} records</div></div><div className="card"><CardHeader title="Fleet health" subtitle="Evidence-backed signals, not predictive maintenance" /><div className="split-stat"><div><span>Operating</span><strong style={{ display: "block" }}>{healthy} / {visibleAssets.length}</strong></div><StatusPill tone="good">{visibleAssets.length ? `${Math.round(healthy / visibleAssets.length * 100)}%` : "—"}</StatusPill></div><div className="split-stat"><div><span>Needs review</span><strong style={{ display: "block" }}>{needsReview}</strong></div><StatusPill tone="warn">{needsReview ? "Attention" : "Clear"}</StatusPill></div><div className="alert" style={{ marginTop: 18 }}><CircleAlert className="svg-icon" style={{ color: "#f4ad56" }} /><div><strong>Review before engineering use</strong><span>Asset health is a review signal and does not predict failure.</span></div></div></div></div>
    <div className="card table-card section"><CardHeader title="Equipment register" subtitle="Stable IDs make asset evidence traceable" action={<Link href="/ecms" className="btn small">View related ECMs <ArrowRight className="svg-icon" /></Link>} /><div className="table-scroll"><table className="data-table"><thead><tr><th>Equipment</th><th>System / location</th><th>Rating</th><th>Health</th><th>Criticality</th><th>Confidence</th><th>Status</th></tr></thead><tbody>{visibleAssets.map((asset) => <tr key={asset.id}><td><strong>{asset.name}</strong><div className="card-subtitle">{asset.id} · {asset.kind}</div></td><td>{asset.system}<div className="card-subtitle">{asset.location}</div></td><td className="mono-value">{asset.rating}</td><td><div style={{ display: "flex", alignItems: "center", gap: 8 }}><Gauge className="svg-icon" style={{ color: asset.health < 75 ? "#f4ad56" : "var(--cyan)" }} />{asset.health}%</div></td><td><StatusPill tone={asset.criticality === "High" ? "orchid" : "default"}>{asset.criticality}</StatusPill></td><td><ConfidencePill grade={asset.confidence} /></td><td><StatusPill tone={asset.status === "Operating" ? "good" : asset.status === "Needs review" ? "warn" : "default"}>{asset.status}</StatusPill></td></tr>)}</tbody></table></div></div>
  </div>;
}
